### ISSUE TITLE
Issue when parsing SEC data

### ISSUE THREAD

**Issue by dinghino** [dinghino/stocks-historical-data#7]
```Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "main", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "./main.py", line 7, in <module>
    cli()
  File "./cli/cli.py", line 13, in start
    entry.run(settings)
  File "./cli/entry.py", line 18, in run
    utils.run_menu(get_menu(), settings)
  File "./cli/utils.py", line 21, in run_menu
    menu_exit = handle_choice(menu_items, choice, settings)
  File "./cli/utils.py", line 10, in handle_choice
    return menu_items[choice][1](settings)
  File "./cli/entry.py", line 35, in handle_run_scraper
    scraper.run()
  File "./scraper/stocks.py", line 52, in run
    self.parser.parse(response)
  File "./scraper/components/parsers/base_parser.py", line 63, in parse
    for row in reader:
  File "/usr/lib/python3.6/codecs.py", line 1041, in iterdecode
    output = decoder.decode(input)
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbb in position 35: invalid start byte
```

Error comes when trying to parse one of the sec files with a long list of tickers and a wide date range.
Doesn't seem related specifically to the settings of the run but it might as well be

## Settings
```
Current Options
Start   2019-05-01
End     2020-01-01
Type    Aggregate File
Path    ./data/output/
Tickers A, AAP, ABBV, ABMD, ABT, ACN, ADBE, AEE, AES, AFL, AKAM, ALB, ALGN, ALK, ALL, ALLE, ALXN, AMCR, AMD, AMZN, AOS, APD, ARE, ATVI, GOOG, GOOGL, LNT, MMM, MO
Sources SEC FTDs
```

The issue seems to be in the `csv.reader` built in the `SecFtdParser` class and returned to process. when the loop start on the iterator it crashes.

Doesn't crash on the first extraction though, when we try to extract the header

**Comment by dinghino** [comment]
For now it's solved adding `error='replace'` to the csv.reader object. I don't like it much, I think, but it solves the issue and the output seems as expected
